---
- name: Install nginx.
  package:
    name: '{{ nginx_package_name }}'
    state: present
- name: Template out the site configuration.
  template:
    src: site.conf.j2
    dest: '{{ nginx_site_conf_path }}'
    owner: '{{ nginx_owner }}'
    group: '{{ nginx_group }}'
    mode: 0644
- name: Create the site directory.
  file:
    path: '{{ nginx_root_dir }}'
    owner: '{{ nginx_owner }}'
    group: '{{ nginx_group }}'
    mode: u=rwX,g=r,o=r
    state: directory
- name: Template out the site.
  template:
    src: site.html.j2
    dest: '{{ nginx_site_index_path }}'
    owner: '{{ nginx_owner }}'
    group: '{{ nginx_group }}'
    mode: 0644
- name: Disable default nginx site.
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
- name: Restart nginx
  service:
    name: nginx
    state: restarted
